In [1]:
# problem
hl = 3
hr = 1
ul = -0.5
ur = 0.5

# Spatial domain
ax = -5
bx = 5
ay = -1
by = 2.5

meqn = 2  # Number of equations in the system

# Gravity
g = 1

# Temporal domain
to = 0
Tfinal = 2

cfl = 0.9


mq = 0 # mq = 0 : Height field
       # mq = 1 : Momentum field
    
mx = 32

h = 0.5
    
# Estimate maximum wave speed.  Note that this will change with time, so we have to find a 
# maximum that works for t in [0,T]
umax = 1.7

In [2]:
%matplotlib notebook
%pylab
%reload_ext autoreload
%autoreload 2

import Riemann_solver 

Riemann_solver.Rieman_solvers(hl,ul,hr,ur, mq, umax, g,ax,bx, ay,by,mx,h, \
                   to, Tfinal,meqn,cfl)

Using matplotlib backend: nbAgg
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib
[[ 3.   1. ]
 [-1.5  0.5]]
solver used is: forestclaw
dt = 1.5385e-01
Number of time steps = 13
Computational time = 1.9849e-02 seconds
solver used is: Gauss_Newton based
dt = 1.5385e-01
Number of time steps = 13
Computational time = 8.6021e-04 seconds
solver used is: Gauss_Newton based
dt = 1.5385e-01
Number of time steps = 13
Computational time = 8.6403e-04 seconds
solver used is: Gauss_Newton based
dt = 1.5385e-01
Number of time steps = 13
Computational time = 9.4318e-04 seconds


<IPython.core.display.Javascript object>

[[ 2.99999649 -1.49999888]
 [ 3.00000578 -1.50000811]
 [ 3.00000856 -1.4999843 ]
 [ 2.99999525 -1.49999665]
 [ 3.0000152  -1.49999745]
 [ 3.00000254 -1.50000554]
 [ 3.00000059 -1.50000163]
 [ 2.99998299 -1.50001048]
 [ 3.00000865 -1.49998193]
 [ 2.99999609 -1.50001029]
 [ 3.00000021 -1.50000745]
 [ 2.99998951 -1.49999259]
 [ 3.00000888 -1.50000437]
 [ 2.99999289 -1.49997854]
 [ 3.000007   -1.49997722]
 [ 2.99999891 -1.49999959]
 [ 1.00001146  0.4999994 ]
 [ 0.99998593  0.50000548]
 [ 1.00002587  0.50000948]
 [ 1.00000758  0.49999256]
 [ 1.00000707  0.50000561]
 [ 0.99999386  0.49999755]
 [ 0.99999348  0.49998905]
 [ 0.99998008  0.49999545]
 [ 1.00000945  0.49999192]
 [ 0.99999241  0.49999339]
 [ 1.00000226  0.49998948]
 [ 1.00000479  0.49999141]
 [ 1.00000272  0.50000366]
 [ 1.00000917  0.50000679]
 [ 1.00001891  0.49998556]
 [ 1.0000114   0.49999408]]
(32, 2)
[[-1.03108458e-06  6.47521253e-08]
 [-1.03108458e-06  6.47521253e-08]]
[[ 3.0000075  -1.49999517]
 [ 2.99998446 -1.49999395]
 [

[[ 3.00000677 -1.50001741]
 [ 3.00001833 -1.50001515]
 [ 2.99999127 -1.4999872 ]
 [ 2.99999402 -1.50001093]
 [ 3.00000302 -1.50000807]
 [ 2.99999319 -1.50000251]
 [ 3.00000389 -1.50000924]
 [ 2.41102484 -0.34193803]
 [ 2.25708318 -0.09187653]
 [ 2.10068367  0.13295841]
 [ 1.94945203  0.32932952]
 [ 1.80222584  0.49412399]
 [ 1.66153219  0.63113453]
 [ 1.52719421  0.73873146]
 [ 1.40470011  0.81984614]
 [ 1.30297859  0.8717189 ]
 [ 1.24480069  0.89606236]
 [ 1.23546788  0.89635358]
 [ 1.23461145  0.89466834]
 [ 1.23201718  0.88950437]
 [ 1.22916902  0.88399878]
 [ 1.21906588  0.8654141 ]
 [ 1.18875746  0.81094566]
 [ 1.10943939  0.67426149]
 [ 1.02826279  0.54319003]
 [ 1.0000112   0.4999913 ]
 [ 0.9999896   0.50001708]
 [ 0.99998626  0.50000446]
 [ 1.00000998  0.49998406]
 [ 1.00000702  0.49999938]
 [ 1.00000166  0.49999419]
 [ 0.99998212  0.49999902]]
(32, 2)
[[-1.52895824e-06  1.20271765e-05]
 [ 1.36132586e-06 -9.26047989e-06]]
[[ 2.9999846  -1.50000463]
 [ 2.99999739 -1.500007  ]
 [